### ISSUE TITLE
Modern Features Option?

### ISSUE THREAD

**Issue by soup587** [CyborgCabbage/cabbagebeta#2]
I think it'd be nice if there was an option to generate newer features such as villages, biomes, ores, etc while keeping the beta terrain. Modern Beta does this and it's really nice for playability.

**Comment by ruvaldak** [comment]
This mod does have that if you compile the latest version, however it's not complete as the world gen doesn't generate oceans or cave biomes, meaning various island-only biomes like mushroom fields, ocean-specific structures like boat ruins, ocean ruins, and ocean monuments don't spawn, and anything else related to the lack of those things generating. It's quite unfortunate.
